# Generated by Django 5.1 on 2024-09-04 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import djmoney.models.fields
import utils.db


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roles", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Break",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(blank=True, null=True)),
                ("start", utils.db.NormalizedDateTimeField(blank=True, null=True)),
                ("end", utils.db.NormalizedDateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="roles.provider",
                    ),
                ),
            ],
            bases=(models.Model, utils.db.TimeStampedModelMixin),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("GBP", "British Pound"),
                            ("CAD", "Canadian Dollar"),
                            ("CZK", "Czech Koruna"),
                            ("DKK", "Danish Krone"),
                            ("EUR", "Euro"),
                            ("MDL", "Moldovan Leu"),
                            ("NOK", "Norwegian Krone"),
                            ("PLN", "Polish Zloty"),
                            ("RON", "Romanian Leu"),
                            ("SEK", "Swedish Krona"),
                            ("CHF", "Swiss Franc"),
                            ("USD", "US Dollar"),
                            ("UAH", "Ukrainian Hryvnia"),
                        ],
                        default="UAH",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="UAH", max_digits=14, null=True
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("start", utils.db.NormalizedDateTimeField(blank=True, null=True)),
                ("end", utils.db.NormalizedDateTimeField(blank=True, null=True)),
                ("is_canceled", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="roles.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="services.service"
                    ),
                ),
            ],
            bases=(models.Model, utils.db.TimeStampedModelMixin),
        ),
        migrations.CreateModel(
            name="Vacation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacations",
                        to="roles.provider",
                    ),
                ),
            ],
            bases=(models.Model, utils.db.TimeStampedModelMixin),
        ),
    ]
