# Generated by Django 5.1 on 2024-09-04 19:55

from django.db import migrations, models

import djmoney.models.fields
import utils.db


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Service name")),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("GBP", "British Pound"),
                            ("CAD", "Canadian Dollar"),
                            ("CZK", "Czech Koruna"),
                            ("DKK", "Danish Krone"),
                            ("EUR", "Euro"),
                            ("MDL", "Moldovan Leu"),
                            ("NOK", "Norwegian Krone"),
                            ("PLN", "Polish Zloty"),
                            ("RON", "Romanian Leu"),
                            ("SEK", "Swedish Krona"),
                            ("CHF", "Swiss Franc"),
                            ("USD", "US Dollar"),
                            ("UAH", "Ukrainian Hryvnia"),
                        ],
                        default="UAH",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="UAH", max_digits=14, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=255, null=True, verbose_name="Description")),
                ("duration", utils.db.NormalizedDurationField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "providers",
                    models.ManyToManyField(related_name="services", to="roles.provider", verbose_name="Providers"),
                ),
            ],
            bases=(models.Model, utils.db.TimeStampedModelMixin),
        ),
    ]
