# Generated by Django 5.1 on 2024-08-30 19:37

from django.db import migrations

import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tz",
            field=timezone_field.fields.TimeZoneField(default="Europe/Vienna", use_pytz=False, verbose_name="Timezone"),
        ),
    ]
