# Generated by Django 5.1 on 2024-08-23 18:15

from django.db import migrations

import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tz",
            field=timezone_field.fields.TimeZoneField(default="Europe/Kyiv", use_pytz=False, verbose_name="Timezone"),
        ),
    ]
