# Generated by Django 5.1 on 2024-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="paid_until",
            field=models.DateField(null=True),
        ),
    ]
