# Generated by Django 5.1 on 2024-08-28 13:56

from django.db import migrations

import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0002_user_tz"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="currency",
            field=djmoney.models.fields.CurrencyField(default=None, max_length=3),
        ),
    ]
